#!/bin/bash

source /etc/default/munin-docsis

echoerr() { echo "$@" 1>&2; }

case $1 in
   config)
        echo "graph_title Unitymedia Segmentauslastung DOCSIS ${CITY}
graph_args --base 1000 -l 0 -u ${TOTALMAXRATE}
graph_vlabel Bit/s
graph_info Anzeige der Auslastung der Downstream Kanaele Unitymedia in ${CITY}
graph_category unitymedia
"
	COUNTER=0
	for freq in $freqs
	do
		freqMhz=`expr $freq / 1000000`
		# Erste Linie
		if [ $COUNTER -eq 0 ]; then
                echo "$freq.label $freqMhz MHz Auslastung in Bit/sec
$freq.draw AREA
$freq.warning ${CHAN_WARN}
$freq.critical ${CHAN_CRIT}
$freq.colour ${freqColor[$freq]}
"
		else
		# Standardfall
		echo "$freq.label $freqMhz MHz Auslastung in Bit/sec
$freq.draw STACK
$freq.warning ${CHAN_WARN}
$freq.critical ${CHAN_CRIT}
$freq.colour ${freqColor[$freq]}
"
		fi
		COUNTER=`expr $COUNTER + 1`
	done
	# Ab 80 proz. erhoehte wachsamkeit ab 90 proz. ueberlastung (quelle UM-MB inoff.)
	echo "sum.label Gesamtauslastung in Bit/sec
sum.draw LINE2
sum.warning ${TOTAL_WARN}
sum.critical ${TOTAL_CRIT}
sum.colour 4D4D4D
"
        exit 0
;;
esac

# give the content of the bandwidth utilization measurement file
cat $DATAFILE 
