#!/bin/bash

source etc/defaults/munin-docsis

echoerr() { echo "$@" 1>&2; }

# configure stick

# disable sleep mode
sudo /usr/local/bin/disableDVBSleep.sh

# set stick to DVB-C mode
sudo /usr/bin/dvb-fe-tool -d DVBC/ANNEX_A &> /dev/null

case $1 in
   config)
        echo "graph_title Unitymedia Segmentauslastung DOCSIS ${CITY}
graph_args --base 1000 -l 0 -u ${TOTALMAXRATE}
graph_vlabel Bit/s
graph_info Anzeige der Auslastung der Downstream Kanaele Unitymedia in ${CITY}
graph_category unitymedia
"
	COUNTER=0
	for freq in $freqs
	do
		freqMhz=`expr $freq / 1000000`
		# Erste Linie
		if [ $COUNTER -eq 0 ]; then
                echo "$freq.label $freqMhz MHz Auslastung in Bit/sec
$freq.draw AREA
$freq.warning ${CHAN_WARN}
$freq.critical ${CHAN_CRIT}
$freq.colour ${freqColor[$freq]}
"
		else
		# Standardfall
		echo "$freq.label $freqMhz MHz Auslastung in Bit/sec
$freq.draw STACK
$freq.warning ${CHAN_WARN}
$freq.critical ${CHAN_CRIT}
$freq.colour ${freqColor[$freq]}
"
		fi
		COUNTER=`expr $COUNTER + 1`
	done
	# Ab 80 proz. erhoehte wachsamkeit ab 90 proz. ueberlastung (quelle UM-MB inoff.)
	echo "sum.label Gesamtauslastung in Bit/sec
sum.draw LINE2
sum.warning ${TOTAL_WARN}
sum.critical ${TOTAL_CRIT}
sum.colour 4D4D4D
"
        exit 0
;;
esac

sum=0
for freq in $freqs
do
	# Tune to frequency
	sudo ${DVBTUNE} -f $freq -s 6952 -qam 256 &> /dev/null
	# Get bandwidth usage
	bandwidth=`timeout 3 sudo ${DVBSNOOP} -adapter 0 -s bandwidth 8190 -n 5000 -hideproginfo | awk -F: 'END { print $NF }' | sed 's/^[ t]*//' | awk '{print $1 * 1000}'`
	echo $freq.value $bandwidth
	sum=$( expr $sum + $bandwidth )
done
echo sum.value $sum
