#!/bin/bash
DVBTUNE=/usr/bin/dvbtune
DVBSNOOP=/usr/bin/dvbsnoop
CITY="Aachen"
MAXPERCHAN=55000 # kBit/s
NCHANS=21
TOTALMAXRATE=$( expr $MAXPERCHAN \* ${NCHANS} \* 1000)
TOTAL_WARN=$(expr ${TOTALMAXRATE} \* 8 / 10)
TOTAL_CRIT=$(expr ${TOTALMAXRATE} \* 9 / 10)

CHAN_WARN=$(expr ${MAXPERCHAN} \* 1000 \* 8 / 10)
CHAN_CRIT=$(expr ${MAXPERCHAN} \* 1000 \* 9 / 10)

# Unitymedia Internet Downstream Belegung
# Quelle: http://www.unitymedia-kabelbw-helpdesk.de/tv/nrw_he-digital-tv.html
# 578,586,602 MHz Quelle: Intern UM.
# Weitere Quelle: http://www.unitymediakabelbwforum.de/viewtopic.php?f=80&t=18777&start=10#p205712
freqs="530000000 538000000 554000000 562000000 570000000 578000000 586000000 594000000 602000000 618000000 626000000 634000000 642000000 650000000 658000000 666000000 674000000 682000000 690000000 698000000 706000000"
declare -A freqColor
freqColor[530000000]=4839FE
freqColor[538000000]=483CFE
freqColor[554000000]=484FFE
freqColor[562000000]=4852FE
freqColor[570000000]=4855FE
freqColor[578000000]=4858FE
freqColor[586000000]=485BFE
freqColor[594000000]=485EFF
freqColor[602000000]=4861FE
freqColor[618000000]=4864FE
freqColor[626000000]=4867FE
freqColor[634000000]=486AFE
freqColor[642000000]=486DFE
freqColor[650000000]=4870FE
freqColor[658000000]=4873FE
freqColor[666000000]=4876FE
freqColor[674000000]=4879FE
freqColor[682000000]=487CFE
freqColor[690000000]=487FFE
freqColor[698000000]=4882FE
freqColor[706000000]=4885FE

echoerr() { echo "$@" 1>&2; }

# configure stick

# disable sleep mode
sudo /usr/local/bin/disableDVBSleep.sh

# set stick to DVB-C mode
sudo /usr/bin/dvb-fe-tool -d DVBC/ANNEX_A &> /dev/null

case $1 in
   config)
        echo "graph_title Unitymedia Segmentauslastung DOCSIS ${CITY}
graph_args --base 1000 -l 0 -u ${TOTALMAXRATE}
graph_vlabel Bit/s
graph_info Anzeige der Auslastung der Downstream Kanaele Unitymedia in ${CITY}
graph_category unitymedia
"
	COUNTER=0
	for freq in $freqs
	do
		freqMhz=`expr $freq / 1000000`
		# Erste Linie
		if [ $COUNTER -eq 0 ]; then
                echo "$freq.label $freqMhz MHz Auslastung in Bit/sec
$freq.draw AREA
$freq.warning ${CHAN_WARN}
$freq.critical ${CHAN_CRIT}
$freq.colour ${freqColor[$freq]}
"
		else
		# Standardfall
		echo "$freq.label $freqMhz MHz Auslastung in Bit/sec
$freq.draw STACK
$freq.warning ${CHAN_WARN}
$freq.critical ${CHAN_CRIT}
$freq.colour ${freqColor[$freq]}
"
		fi
		COUNTER=`expr $COUNTER + 1`
	done
	# Ab 80 proz. erhoehte wachsamkeit ab 90 proz. ueberlastung (quelle UM-MB inoff.)
	echo "sum.label Gesamtauslastung in Bit/sec
sum.draw LINE2
sum.warning ${TOTAL_WARN}
sum.critical ${TOTAL_CRIT}
sum.colour 4D4D4D
"
        exit 0
;;
esac

sum=0
for freq in $freqs
do
	# Tune to frequency
	sudo ${DVBTUNE} -f $freq -s 6952 -qam 256 &> /dev/null
	# Get bandwidth usage
	bandwidth=`timeout 3 sudo ${DVBSNOOP} -adapter 0 -s bandwidth 8190 -n 5000 -hideproginfo | awk -F: 'END { print $NF }' | sed 's/^[ t]*//' | awk '{print $1 * 1000}'`
	echo $freq.value $bandwidth
	sum=$( expr $sum + $bandwidth )
done
echo sum.value $sum
